language: csharp
solution: TextExtraction.sln
install:
  - nuget restore TextExtraction.sln
  - nuget install NUnit.Runners -Version 3.5 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TextExtraction.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./TextExtraction.Tests/bin/Release/TextExtraction.Tests.dll
